/*!CK:1967762923!*//*1439789282,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["sDZjD"]); }

__d("P2PTransferStatus",[],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports={PENDING_SENDER_MANUAL_REVIEW:1,PENDING_SENDER_VERIFICATION:2,CANCELED_SENDER_RISK:3,PENDING_RECIPIENT_NUX:4,CANCELED_DECLINED:5,PENDING_RECIPIENT_VERIFICATION:6,PENDING_RECIPIENT_MANUAL_REVIEW:7,PENDING_RECIPIENT_PROCESSING:8,PENDING_PUSH_FAIL:9,CANCELED_RECIPIENT_RISK:10,CANCELED_SYSTEM_FAIL:11,CANCELED_EXPIRED:12,COMPLETED:13,INTERMEDIATE_PROCESSING:14,PENDING_SENDER_INITED:15,CANCELED_SAME_CARD:16,PENDING_SENDER_VERIFICATION_PROCESSING:17,PENDING_RECIPIENT_VERIFICATION_PROCESSING:18};},null,{});
__d('AbstractTextArea.react',['AbstractTextFieldMixin.react','React','cx'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();var k=i.createClass({displayName:'AbstractTextArea',mixins:[h],renderTextField:function(){return this.setTextFieldPropsOn(i.createElement('textarea',{className:"_58an",tabIndex:this.props.tabIndex,onClick:this.props.onClick,onKeyUp:this.props.onKeyUp,rows:this.props.rows}));}});f.exports=k;},null);
__d('XUIOverlayButton.react',['AbstractButton.react','React','cx','joinClasses'],function a(b,c,d,e,f,g,h,i,j,k){if(c.__markCompiled)c.__markCompiled();var l=Object.assign||function(n){for(var o=1;o<arguments.length;o++){var p=arguments[o];for(var q in p)if(Object.prototype.hasOwnProperty.call(p,q))n[q]=p[q];}return n;},m=i.createClass({displayName:'XUIOverlayButton',render:function(){var n="_51tl selected";return (i.createElement(h,l({},this.props,{className:k(this.props.className,n)})));}});f.exports=m;},null);
__d('XUIPagerButtons.react',['React','XUIButtonGroup.react','invariant'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();var k=h.createClass({displayName:'XUIPagerButtons',render:function(){!(this.props.children.length===2)?j(0):undefined;return (h.createElement(i,this.props,this.props.children));}});f.exports=k;},null);
__d('BlueBarController',['Bootloader','CSS'],function a(b,c,d,e,f,g,h,i){if(c.__markCompiled)c.__markCompiled();g.init=function(j){if('getBoundingClientRect' in j){var k=function(){var l=j.getBoundingClientRect(),m=Math.round(l.top)-document.documentElement.clientTop;i.conditionClass(j.firstChild,'fixed_elem',m<=0);};k();h.loadModules(["Event"],function(l){l.listen(window,'scroll',k);});}};},null);
__d('MessengerButton.react',['ReactComponentWithPureRenderMixin','React','cx','joinClasses'],function a(b,c,d,e,f,g,h,i,j,k){if(c.__markCompiled)c.__markCompiled();'use strict';var l=Object.assign||function(p){for(var q=1;q<arguments.length;q++){var r=arguments[q];for(var s in r)if(Object.prototype.hasOwnProperty.call(r,s))p[s]=r[s];}return p;};function m(p,q){var r={};for(var s in p){if(q.indexOf(s)>=0)continue;if(!Object.prototype.hasOwnProperty.call(p,s))continue;r[s]=p[s];}return r;}var n=i.PropTypes,o=i.createClass({displayName:'MessengerButton',mixins:[h],propTypes:{label:n.string.isRequired,type:n.oneOf(['primary','secondary']).isRequired,use:n.oneOf(['default','danger']).isRequired},getDefaultProps:function(){return {use:'default'};},handleLinkClick:function(p){if(this.props.disabled){p.preventDefault();}else if(this.props.onClick)this.props.onClick(p);},render:function(){var p=this.props,q=p.className,r=p.label,s=m(p,['className','label']);return (i.createElement('a',l({className:k("_3quh"+(' '+"_30yy")+(this.props.type==='primary'?' '+"_2t_":'')+(this.props.type==='secondary'?' '+"_2u0":'')+(this.props.use==='danger'?' '+"_3ay_":'')+(this.props.disabled?' '+"_4zab":''),q),href:'#'},s,{onClick:this.handleLinkClick}),r));}});f.exports=o;},null);
__d('MessengerDialog.react',['LayerFadeOnHide','LayerHideOnEscape','React','XUIDialog.react','cx','joinClasses'],function a(b,c,d,e,f,g,h,i,j,k,l,m){if(c.__markCompiled)c.__markCompiled();'use strict';var n=Object.assign||function(q){for(var r=1;r<arguments.length;r++){var s=arguments[r];for(var t in s)if(Object.prototype.hasOwnProperty.call(s,t))q[t]=s[t];}return q;},o=j.PropTypes,p=j.createClass({displayName:'MessengerDialog',propTypes:{onToggle:o.func.isRequired,repositionOnUpdate:o.bool,shown:o.bool,type:o.oneOf(['alert','default']),width:o.number},getDefaultProps:function(){return {repositionOnUpdate:false,shown:true,type:'alert',width:400};},componentDidUpdate:function(){if(this.props.repositionOnUpdate)setTimeout((function(){if(this.isMounted()&&this.refs.dialog&&this.refs.dialog.layer)this.refs.dialog.layer.updatePosition();}).bind(this),0);},render:function(){return (j.createElement(k,n({behaviors:{LayerFadeOnHide:h,LayerHideOnEscape:i}},this.props,{className:m("_4ebx",this.props.className),ref:'dialog'}),j.createElement('div',{className:"_4eby"+(this.props.type==='alert'?' '+"_2c9g":'')+(this.props.type==='default'?' '+"_2c9i":'')},this.props.children)));}});f.exports=p;},null);
__d('MessengerDialogBody.react',['React','cx','joinClasses'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();'use strict';var k=h.createClass({displayName:'MessengerDialogBody',render:function(){return (h.createElement('div',{className:j("_4eb-",this.props.className)},this.props.children));}});f.exports=k;},null);
__d('MessengerDialogFooter.react',['LeftRight.react','React','cx','joinClasses'],function a(b,c,d,e,f,g,h,i,j,k){if(c.__markCompiled)c.__markCompiled();'use strict';var l=i.PropTypes,m=i.createClass({displayName:'MessengerDialogFooter',propTypes:{leftContent:l.object},render:function(){return (i.createElement('div',{className:k("_4eb_",this.props.className)},i.createElement(h,null,i.createElement('div',{className:"_2_d1"},this.props.leftContent),i.createElement('div',null,this.props.children))));}});f.exports=m;},null);
__d('MessengerDialogHeader.react',['React','cx','joinClasses'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();'use strict';var k=h.createClass({displayName:'MessengerDialogHeader',render:function(){return (h.createElement('h4',{className:j("_4ebz",this.props.className)},this.props.children));}});f.exports=k;},null);
__d('MessengerDialogTitle.react',['React','cx','joinClasses'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();'use strict';var k=h.createClass({displayName:'MessengerDialogTitle',render:function(){return (h.createElement('div',{className:j("_19jt",this.props.className)},this.props.children));}});f.exports=k;},null);
__d("XPaymentSettingNotificationController",["XController"],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports=c("XController").create("\/payment\/settings\/notification\/",{});},null,{});
__d("XPaymentSettingsGetUserBalanceController",["XController"],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports=c("XController").create("\/payment\/settings\/balance\/",{});},null,{});